TRUNCATE TABLE `t_trn_jyuchu_header`;
TRUNCATE TABLE `t_trn_jyuchu_header_simego`;
TRUNCATE TABLE `t_trn_jyuchu_header_sub`;
TRUNCATE TABLE `t_trn_jyuchu_meisai`;
TRUNCATE TABLE `t_trn_jyuchu_meisai_simego`;
ALTER TABLE `t_trn_jyuchu_header` AUTO_INCREMENT = 1;
ALTER TABLE `t_trn_jyuchu_header_simego` AUTO_INCREMENT = 1;
ALTER TABLE `t_trn_jyuchu_meisai` AUTO_INCREMENT = 1;
ALTER TABLE `t_trn_jyuchu_meisai_simego` AUTO_INCREMENT = 1;
ALTER TABLE `t_trn_jyuchu_header_sub` AUTO_INCREMENT = 1;
