use `ne_user1`;
SELECT
`t_trn_jyuchu_header`.`tenpo_code`
,`t_trn_jyuchu_header`.`tenpo_denpyo_no`
,`t_trn_jyuchu_header`.`jyuyou_check_kbn`
,`t_trn_jyuchu_header`.`jyuyou_check_tantou`
,`t_trn_jyuchu_header`.`kakunin_check_kbn`
,`t_trn_jyuchu_header`.`system_message_kbn`
,`t_trn_jyuchu_header`.`mail_jyotai_value`
,`t_trn_jyuchu_header`.`jyuchu_tag`
,`t_trn_jyuchu_header`.`torikomi_syurui_kbn`
,`t_trn_jyuchu_header`.`jyuchu_cancel_kbn`
,`t_trn_jyuchu_header`.`jyuchu_cancel_bi`
,`t_trn_jyuchu_header`.`simego_syusei_bi`
,`t_trn_jyuchu_header`.`jyuchu_jyotai_kbn`
,`t_trn_jyuchu_header`.`jyuchu_tantou_code`
,`t_trn_jyuchu_header`.`hasou_kbn`
,`t_trn_jyuchu_header`.`siharai_kbn`
,`t_trn_jyuchu_header`.`goukei_kin`
,`t_trn_jyuchu_header`.`zei_kin`
,`t_trn_jyuchu_header`.`tesuryo_kin`
,`t_trn_jyuchu_header`.`hasou_kin`
,`t_trn_jyuchu_header`.`sonota_kin`
,`t_trn_jyuchu_header`.`POINT`
,`t_trn_jyuchu_header`.`syohin_kin`
,`t_trn_jyuchu_header`.`bikou`
,`t_trn_jyuchu_header`.`nyukin_kin`
,`t_trn_jyuchu_header`.`nyukin_kbn`
,`t_trn_jyuchu_header`.`nyukin_bi`
,`t_trn_jyuchu_header`.`doukon_kouho_jyuchu_denpyo_no`
,`t_trn_jyuchu_header`.`doukon_saki_jyuchu_denpyo_no`
,`t_trn_jyuchu_header`.`bunkatu_moto_jyuchu_denpyo_no`
,`t_trn_jyuchu_header`.`fukusya_moto_jyuchu_denpyo_no`
,`t_trn_jyuchu_header`.`hukusu_haisou_oyajyuchu_denpyo_no`
,`t_trn_jyuchu_header`.`hukusu_haisou_oya_flg`
,`t_trn_jyuchu_header`.`nouhinsyo_insatusiji_bi`
,`t_trn_jyuchu_header`.`nouhinsyo_hakou_bi`
,`t_trn_jyuchu_header`.`nouhinsyo_text`
,`t_trn_jyuchu_header`.`syuka_kakutei_bi`
,`t_trn_jyuchu_header`.`syuka_jyunjyo`
,`t_trn_jyuchu_header`.`syuka_tantou_code`
,`t_trn_jyuchu_header`.`sagyosya_ran`
,`t_trn_jyuchu_header`.`pic_siji_naiyou`
,`t_trn_jyuchu_header`.`pic_saisyo_sire_code`
,`t_trn_jyuchu_header`.`pic_saisyo_syohin_code`
,`t_trn_jyuchu_header`.`raberu_hakou_bi`
,`t_trn_jyuchu_header`.`raberu_hakou_flg`
,`t_trn_jyuchu_header`.`haisou_bi`
,`t_trn_jyuchu_header`.`jikantaisitei_kbn`
,`t_trn_jyuchu_header`.`binsyu_kbn`
,`t_trn_jyuchu_header`.`seal1_kbn`
,`t_trn_jyuchu_header`.`seal2_kbn`
,`t_trn_jyuchu_header`.`seal3_kbn`
,`t_trn_jyuchu_header`.`seal4_kbn`
,`t_trn_jyuchu_header`.`eigyosyo_dome_kbn`
,`t_trn_jyuchu_header`.`eigyosyo_name`
,`t_trn_jyuchu_header`.`okurijyo_kbn`
,`t_trn_jyuchu_header`.`ondo_kbn`
,`t_trn_jyuchu_header`.`gift_flg`
,`t_trn_jyuchu_header`.`hasou_denpyo_no`
,`t_trn_jyuchu_header`.`credit_kbn`
,`t_trn_jyuchu_header`.`credit_card_no`
,`t_trn_jyuchu_header`.`credit_meigi_nin`
,`t_trn_jyuchu_header`.`credit_yukou_kigen`
,`t_trn_jyuchu_header`.`credit_syonin_no`
,`t_trn_jyuchu_header`.`credit_syonin_kin`
,`t_trn_jyuchu_header`.`credit_syonin_kbn`
,`t_trn_jyuchu_header`.`credit_syonin_bi`
,`t_trn_jyuchu_header`.`credit_syoninji_rate`
,`t_trn_jyuchu_header`.`credit_siharai_kaisu`
,`t_trn_jyuchu_header`.`credit_osori_kbn`
,`t_trn_jyuchu_header`.`credit_syonin_fax_insatu_bi`
,`t_trn_jyuchu_header`.`kokyaku_kbn`
,`t_trn_jyuchu_header`.`kokyaku_code`
,`t_trn_jyuchu_header`.`jyuchu_name`
,`t_trn_jyuchu_header`.`jyuchu_kana`
,`t_trn_jyuchu_header`.`jyuchu_yubin_bangou`
,`t_trn_jyuchu_header`.`jyuchu_jyusyo1`
,`t_trn_jyuchu_header`.`jyuchu_jyusyo2`
,`t_trn_jyuchu_header`.`jyuchu_denwa`
,`t_trn_jyuchu_header`.`jyuchu_fax`
,`t_trn_jyuchu_header`.`jyuchu_mail_adr`
,`t_trn_jyuchu_header`.`tokusoku_kaisi_bi`
,`t_trn_jyuchu_header`.`saisyu_tokusoku_bi`
,`t_trn_jyuchu_header`.`tokusoku_cnt`
,`t_trn_jyuchu_header`.`hasou_name`
,`t_trn_jyuchu_header`.`hasou_kana`
,`t_trn_jyuchu_header`.`hasou_yubin_bangou`
,`t_trn_jyuchu_header`.`hasou_jyusyo1`
,`t_trn_jyuchu_header`.`hasou_jyusyo2`
,`t_trn_jyuchu_header`.`hasou_denwa`
,`t_trn_jyuchu_header`.`hasou_fax`
,`t_trn_jyuchu_header`.`gaikoku_goukei_kin`
,`t_trn_jyuchu_header`.`gaikoku_zei_kin`
,`t_trn_jyuchu_header`.`gaikoku_tesuryo_kin`
,`t_trn_jyuchu_header`.`gaikoku_hasou_kin`
,`t_trn_jyuchu_header`.`gaikoku_sonota_kin`
,`t_trn_jyuchu_header`.`gaikoku_syohin_kin`
,`t_trn_jyuchu_header`.`gaikoku_nyukin_kin`
,`t_trn_jyuchu_header`.`e_txt`
,`t_trn_jyuchu_header`.`syuka_yotei_bi`
,`t_trn_jyuchu_header`.`sakujyo_flg`
,`t_trn_jyuchu_meisai`.`jyuchu_meisai_gyo`
,`t_trn_jyuchu_meisai`.`tenpo_denpyo_no`
,`t_trn_jyuchu_meisai`.`tenpo_meisai_gyo`
,`t_trn_jyuchu_meisai`.`syohin_code`
,`t_trn_jyuchu_meisai`.`syohin_name`
,`t_trn_jyuchu_meisai`.`jyuchu_su`
,`t_trn_jyuchu_meisai`.`syohin_tnk`
,`t_trn_jyuchu_meisai`.`jyuchuji_genka_tnk`
,`t_trn_jyuchu_meisai`.`gaikoku_syohin_tnk`
,`t_trn_jyuchu_meisai`.`kake_ritu`
,`t_trn_jyuchu_meisai`.`syokei_kin`
,`t_trn_jyuchu_meisai`.`syohin_option`
,`t_trn_jyuchu_meisai`.`cancel_kbn`
,`t_trn_jyuchu_meisai`.`doukon_moto_jyuchu_denpyo_no`
,`t_trn_jyuchu_meisai`.`doukon_moto_jyuchu_meisai_gyo`
,`t_trn_jyuchu_meisai`.`bunkatu_moto_jyuchu_meisai_gyo`
,`t_trn_jyuchu_meisai`.`fukusya_moto_jyuchu_meisai_gyo`
,`t_trn_jyuchu_meisai`.`hukusu_haisou_oyajuchu_denpyo_no`
,`t_trn_jyuchu_meisai`.`hikiate_su`
,`t_trn_jyuchu_meisai`.`hikiate_bi`
,`t_trn_jyuchu_meisai`.`jyuchuji_toriatukai_kbn`
,`t_trn_jyuchu_meisai`.`jyuchuji_syohin_kbn`
,`t_trn_jyuchu_meisai`.`ryohin_henpin_su`
,`t_trn_jyuchu_meisai`.`furyohin_henpin_su`
,`t_trn_jyuchu_meisai`.`henpin_jiyu_kbn`
,`t_trn_jyuchu_meisai`.`yoyaku_hikiate_su`
,`t_trn_jyuchu_meisai`.`moto_jyuchu_meisai_gyo`
,`t_trn_jyuchu_meisai`.`sakusei_tantou`
,`t_trn_jyuchu_meisai`.`saisyu_kousin_tantou`
,`t_trn_jyuchu_meisai`.`sakujyo_flg`
FROM `t_trn_jyuchu_header`
INNER JOIN 
`t_trn_jyuchu_meisai`
ON
`t_trn_jyuchu_meisai`.`tenpo_denpyo_no`=`t_trn_jyuchu_header`.`tenpo_denpyo_no`
WHERE `t_trn_jyuchu_header`.`torikomi_bi` >= DATE(NOW());