#!/bin/sh

# branch name: oki_{ticket_number}
# Premise: redmine
if [ "$2" == "" ] ; then
    mv $1 $1.tmp
    echo "\n\nrefs #$(git branch | grep '*' | awk '{print $2}' | sed -e 's/.*_//')" > $1
    cat $1.tmp >> $1
fi

